### ISSUE TITLE
Absolute positioning

### ISSUE THREAD

**Issue by arhtudormorar** [maisano/react-router-transition#13] opened 2016-07-21 11:21 UTC
It took me 2-3 hours to find out that if you don't use absolute positioning, your pages will be created below the existing one

```
<RouteTransition
                  pathname={this.props.pathname}
                  atEnter={{ translateX: 100 }}
                  atLeave={{ translateX: -100 }}
                  atActive={{ translateX: 0}}
                  mapStyles={mapStyles}>
      <div style={{
                  "position": "absolute", "margin-left": "auto",
                  "margin-right": "auto",
                  "left": 0,
                  "right": 0}}>
          <div className="container" style={this.state.containerStyle}>
                  {this.props.children}
          </div>
      </div>
</RouteTransition>
```
 It would be a good idea to specify this in the Readme

**Comment by jacobangel** [comment] 2016-07-21 12:20
Sorry it took you so long to find this. There is a long discussion regarding how to handle this in issue #3. Your input would be welcome there.

Also, it'd be awesome if you could open a Pull Request with modifications to the README that you think would help future people avoid what your ran into.

**Comment by jacobangel** [comment] 2016-07-21 14:23
Closing as duplicate of #3

**Closed by jacobangel** 2016-07-21 14:23 UTC
